PROD:
  DB:
    SCHEMA: cosmos_watchdog
    USER: cosmos_watchdog
    HOST: localhost
    PORT: 5432
    PASSWORD: cosmos_watchdog
  API:
    HOST: localhost
    PORT: 5000
  BOT:
    TOKEN: XXX
    FREQUENCY: 10 #seconds
    CHANNEL_ID: 1234
  SYNCHRONIZER:
    FREQUENCY: 30 #seconds
    VALIDATOR_ADDRESS: osmovaloper1udp8gef365zcqhlxuepewrxuep9thjanuhxcaw
    NOTIFY: True
TEST:
  DB:
    SCHEMA: test_cosmos_watchdog
    USER: cosmos_watchdog
    HOST: localhost
    PORT: 5432
    PASSWORD: cosmos_watchdog
  API:
    HOST: 0.0.0.0
    PORT: 5000
  BOT:
    TOKEN: XXX
    FREQUENCY: 10 #seconds
    CHANNEL_ID: 1234
  SYNCHRONIZER:
    FREQUENCY: 30 #seconds
    VALIDATOR_ADDRESS: osmovaloper1udp8gef365zcqhlxuepewrxuep9thjanuhxcaw
    NOTIFY: True
