version: '3.1'
services:
    cosmos-watchdog:
        image: ${DOCKER_IMAGE:-ghcr.io/astroquirkshq/cosmos-watchdog:main}
        volumes: # Bind the code so changes are reflected immediately in the container
            - .:/app
        ports:
            - 5001:5000
        environment:
            DB_HOST: ${DB_HOST:-postgres}
            DB_PORT: ${DB_PORT:-5432}
            DB_USER: ${DB_USER:-cosmos_watchdog}
            DB_PASSWORD: ${DB_PASSWORD:-cosmos_watchdog}
            HOST: 0.0.0.0 # not localhost so we can access flask from the host
            DB_SCHEMA: ${DB_SCHEMA:-cosmos_watchdog}
        depends_on:
            - postgres
        command: "pipenv run dev"

    postgres:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: ${DB_USER:-cosmos_watchdog}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-cosmos_watchdog}
            POSTGRES_DB: ${DB_SCHEMA:-cosmos_watchdog}
        ports:
            - 5432:5432
